[tool.poetry]
name = "controlnet-plus"
version = "0.1.0"
description = ""
authors = ["xinsir6"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
absl-py = "^2.1.0"
accelerate = "^0.28.0"
aiofiles = "^23.2.1"
aiohttp = "^3.9.3"
aiosignal = "^1.3.1"
albumentations = "^1.4.2"
altair = "^5.3.0"
annotated-types = "^0.6.0"
antlr4-python3-runtime = "^4.9.3"
anyio = "^4.3.0"
appdirs = "^1.4.4"
argon2-cffi = "^23.1.0"
argon2-cffi-bindings = "^21.2.0"
arrow = "^1.3.0"
asttokens = "^2.4.1"
async-lru = "^2.0.4"
async-timeout = "^4.0.3"
attrs = "^23.2.0"
Babel = "^2.14.0"
backcall = "^0.2.0"
beautifulsoup4 = "^4.12.3"
bleach = "^6.1.0"
cachetools = "^5.3.3"
certifi = "^2024.2.2"
cffi = "^1.16.0"
charset-normalizer = "^3.3.2"
click = "^8.1.7"
cmake = "^3.29.0.1"
comm = "^0.2.2"
contourpy = "^1.1.1"
controlnet-aux = "^0.0.9"
cycler = "^0.12.1"
dadaptation = "^3.2"
datasets = "^2.18.0"
debugpy = "^1.8.1"
decorator = "^5.1.1"
deepspeed = "^0.14.0"
defusedxml = "^0.7.1"
diffusers = "^0.27.2"
dill = "^0.3.8"
docker-pycreds = "^0.4.0"
einops = "^0.7.0"
exceptiongroup = "^1.2.0"
executing = "^2.0.1"
fastapi = "^0.110.2"
fastjsonschema = "^2.19.1"
ffmpy = "^0.3.2"
filelock = "^3.13.3"
fonttools = "^4.51.0"
fqdn = "^1.5.1"
frozenlist = "^1.4.1"
fsspec = "^2024.2.0"
ftfy = "^6.2.0"
gitdb = "^4.0.11"
GitPython = "^3.1.42"
google-auth = "^2.29.0"
google-auth-oauthlib = "^1.0.0"
gradio = "^3.41.2"
gradio_client = "^0.5.0"
grpcio = "^1.62.1"
h11 = "^0.14.0"
hjson = "^3.1.0"
httpcore = "^1.0.5"
httpx = "^0.27.0"
huggingface-hub = "^0.22.1"
idna = "^3.6"
imageio = "^2.34.0"
importlib_metadata = "^7.1.0"
importlib_resources = "^6.4.0"
ipykernel = "^6.29.4"
ipython = "^8.12.3"
ipython-genutils = "^0.2.0"
ipywidgets = "^8.1.2"
isoduration = "^20.11.0"
jedi = "^0.19.1"
Jinja2 = "^3.1.3"
joblib = "^1.3.2"
json5 = "^0.9.24"
jsonpointer = "^2.4"
jsonschema = "^4.21.1"
jsonschema-specifications = "^2023.12.1"
jupyter = "^1.0.0"
jupyter-console = "^6.6.3"
jupyter-events = "^0.10.0"
jupyter-lsp = "^2.2.4"
jupyter_client = "^8.6.1"
jupyter_core = "^5.7.2"
jupyter_server = "^2.13.0"
jupyter_server_terminals = "^0.5.3"
jupyterlab = "^4.1.6"
jupyterlab_pygments = "^0.3.0"
jupyterlab_server = "^2.26.0"
jupyterlab_widgets = "^3.0.10"
jupytext = "^1.16.1"
kiwisolver = "^1.4.5"
lazy_loader = "^0.3"
lightning-utilities = "^0.11.2"
lit = "^18.1.2"
loguru = "^0.7.2"
Markdown = "^3.6"
markdown-it-py = "^3.0.0"
MarkupSafe = "^2.1.5"
matplotlib = "^3.7.5"
matplotlib-inline = "^0.1.6"
mdit-py-plugins = "^0.4.0"
mdurl = "^0.1.2"
mistune = "^3.0.2"
mpmath = "^1.3.0"
multidict = "^6.0.5"
multiprocess = "^0.70.16"
nbclassic = "^1.0.0"
nbclient = "^0.10.0"
nbconvert = "^7.16.3"
nbformat = "^5.10.4"
nest-asyncio = "^1.6.0"
networkx = "^3.1"
ninja = "^1.11.1.1"
notebook = "^6.5.4"
notebook_shim = "^0.2.4"
numpy = "^1.24.4"
nvidia-cublas-cu11 = "^11.10.3.66"
nvidia-cublas-cu12 = "^12.1.3.1"
nvidia-cuda-cupti-cu11 = "^11.7.101"
nvidia-cuda-cupti-cu12 = "^12.1.105"
nvidia-cuda-nvrtc-cu11 = "^11.7.99"
nvidia-cuda-nvrtc-cu12 = "^12.1.105"
nvidia-cuda-runtime-cu11 = "^11.7.99"
nvidia-cuda-runtime-cu12 = "^12.1.105"
nvidia-cudnn-cu11 = "^8.5.0.96"
nvidia-cudnn-cu12 = "^8.9.2.26"
nvidia-cufft-cu11 = "^10.9.0.58"
nvidia-cufft-cu12 = "^11.0.2.54"
nvidia-curand-cu11 = "^10.2.10.91"
nvidia-curand-cu12 = "^10.3.2.106"
nvidia-cusolver-cu11 = "^11.4.0.1"
nvidia-cusolver-cu12 = "^11.4.5.107"
nvidia-cusparse-cu11 = "^11.7.4.91"
nvidia-cusparse-cu12 = "^12.1.0.106"
nvidia-nccl-cu11 = "^2.14.3"
nvidia-nccl-cu12 = "^2.19.3"
nvidia-nvjitlink-cu12 = "^12.4.99"
nvidia-nvtx-cu11 = "^11.7.91"
nvidia-nvtx-cu12 = "^12.1.105"
oauthlib = "^3.2.2"
omegaconf = "^2.3.0"
open-clip-torch = "^2.24.0"
openai-clip = "^1.0.1"
opencv-python = "^4.9.0.80"
opencv-python-headless = "^4.9.0.80"
orjson = "^3.10.3"
overrides = "^7.7.0"
packaging = "^24.0"
pandas = "^2.0.3"
pandocfilters = "^1.5.1"
parso = "^0.8.3"
pexpect = "^4.9.0"
pickleshare = "^0.7.5"
pillow = "^10.2.0"
pkgutil_resolve_name = "^1.3.10"
platformdirs = "^4.2.0"
prometheus_client = "^0.20.0"
prompt-toolkit = "^3.0.43"
protobuf = "^4.25.3"
psutil = "^5.9.8"
ptyprocess = "^0.7.0"
pure-eval = "^0.2.2"
py-cpuinfo = "^9.0.0"
pyarrow = "^15.0.2"
pyarrow-hotfix = "^0.6"
pyasn1 = "^0.6.0"
pyasn1_modules = "^0.4.0"
pycparser = "^2.22"
pydantic = "^2.6.4"
pydantic_core = "^2.16.3"
pydub = "^0.25.1"
Pygments = "^2.17.2"
pynvml = "^11.5.0"
pyparsing = "^3.1.2"
python-dateutil = "^2.9.0.post0"
python-json-logger = "^2.0.7"
python-multipart = "^0.0.9"
pytorch-lightning = "^2.2.1"
pytz = "^2024.1"
PyWavelets = "^1.4.1"
PyYAML = "^6.0.1"
pyzmq = "^25.1.2"
qtconsole = "^5.5.1"
QtPy = "^2.4.1"
referencing = "^0.34.0"
regex = "^2023.12.25"
requests = "^2.31.0"
requests-oauthlib = "^2.0.0"
rfc3339-validator = "^0.1.4"
rfc3986-validator = "^0.1.1"
rich = "^13.7.1"
rpds-py = "^0.18.0"
rsa = "^4.9"
ruff = "^0.4.6"
safetensors = "^0.4.2"
scikit-image = "^0.21.0"
scikit-learn = "^1.3.2"
scipy = "^1.10.1"
semantic-version = "^2.10.0"
Send2Trash = "^1.8.3"
sentencepiece = "^0.2.0"
sentry-sdk = "^1.43.0"
setproctitle = "^1.3.3"
shellingham = "^1.5.4"
six = "^1.16.0"
smmap = "^5.0.1"
sniffio = "^1.3.1"
soupsieve = "^2.5"
stack-data = "^0.6.3"
starlette = "^0.37.2"
sympy = "^1.12"
tensorboard = "^2.14.0"
tensorboard-data-server = "^0.7.2"
terminado = "^0.18.1"
threadpoolctl = "^3.4.0"
tifffile = "^2023.7.10"
tiktoken = "^0.6.0"
timm = "^0.6.7"
tinycss2 = "^1.2.1"
tokenizers = "^0.15.2"
toml = "^0.10.2"
tomli = "^2.0.1"
tomlkit = "^0.12.0"
toolz = "^0.12.1"
torch = "^2.0.1"
torchmetrics = "^1.3.2"
torchsde = "^0.2.6"
torchvision = "^0.15.2"
tornado = "^6.4"
tqdm = "^4.66.2"
traitlets = "^5.9.0"
trampoline = "^0.1.2"
transformers = "^4.39.1"
triton = "^2.0.0"
typer = "^0.12.3"
types-python-dateutil = "^2.9.0.20240316"
typing_extensions = "^4.10.0"
tzdata = "^2024.1"
uri-template = "^1.3.0"
urllib3 = "^2.2.1"
uvicorn = "^0.29.0"
voluptuous = "^0.14.2"
wandb = "^0.16.5"
wcwidth = "^0.2.13"
webcolors = "^1.13"
webencodings = "^0.5.1"
websocket-client = "^1.7.0"
websockets = "^11.0.3"
Werkzeug = "^3.0.1"
widgetsnbextension = "^4.0.10"
xformers = "^0.0.22"
xxhash = "^3.4.1"
yarl = "^1.9.4"
zipp = "^3.18.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
